id: P000741
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6894
  title: ཞིང་ནང་གི་རྩ་ངན་མེད་པ་བཟོ་ཐབས་སྐོར་གྱི་ཤེས་བྱ།
  author: ''
  volumes:
    4220d4f17c95488889916d230e57ba37:
      image_group_id: I3CN6896
      title: ''
      volume_number: 1
      total_pages: 155
